package uk.co.bookingAndCollection.security;

public class SecurityConstants {

  static final String SECRET = "SecretKeyToGenJWTs"; // Ideally this key should be generated by SSL Key-Gen lib
  static final long EXPIRATION_TIME = 3600000; //  1 hour
  static final String TOKEN_PREFIX = "ApexCargo ";
  static final String HEADER_STRING = "auth";
  static final String SIGN_UP_URL = "/api/user";
  static final String LOG_IN_URL = "/login";
  static final String BOOKING_URL = "/api/bookings";

}
